### ISSUE TITLE
Text Color in intergrated terminal

### ISSUE THREAD

**Issue by hieumdd** [michael-andreuzza/serendipity#10]
The latest update to the **light** color scheme seems nice, The blue border upon debugging/testing was a nice touch. However I did notice that the color scheme for some text in the intergrated terminal got blended to the background.
I'm using gh cli for reference.
![image](https://user-images.githubusercontent.com/24801365/149910781-8d846ae8-ec77-4696-9f1f-39012749af1d.png)
![image](https://user-images.githubusercontent.com/24801365/149910818-ac908c19-6a1b-4d41-9741-05b1cb0b67bb.png)

**Comment by michael-andreuzza** [comment]
Hey Hieu,

Thank you for finding that issue, I will proceed and fix it.

/Mike

**Comment by michael-andreuzza** [comment]
Well, no w is pushed and you can update the theme in around 10 minutes. Feel free to let me know if that suits you better.

/Mike

**Comment by hieumdd** [comment]
![image](https://user-images.githubusercontent.com/24801365/150050262-78780581-0092-4d31-b9a2-cbf89c5aef8a.png)
Much better now. Thanks Michael
I think the problem was only on windows, mac was fine

**Comment by michael-andreuzza** [comment]
@hieumdd You have the old version here with your light theme.
 https://marketplace.visualstudio.com/items?itemName=wicked-labs.old-serendipity

**Comment by hieumdd** [comment]
Wonderful. Thank you <3

**Comment by michael-andreuzza** [comment]
@hieumdd you are very welcome :-)
