### ISSUE TITLE
Extra space in theme label "Serendipity Midnight" in VSCode

### ISSUE THREAD

**Issue by hedwardd** [michael-andreuzza/serendipity#11]
Greetings! First, love the work. Great job all around.

That said, I wanted to inform you there's a possible typo in the label for the theme "Serendipity Midnight" in VSCode.

It looks like there's an extra space between the words in `package.json` [here](https://github.com/michael-andreuzza/serendipity/blob/785f237cc74ba2060196863ac81cedfb2b8f0fc7/package.json#L36).

Hope that's helpful! Again, awesome stuff.

**Comment by michael-andreuzza** [comment]
Thank you for the heads up Heath! I appreciate :-)
