### ISSUE TITLE
Italics versions missing in the latest update

### ISSUE THREAD

**Issue by joekaiser** [michael-andreuzza/serendipity#12]
The italics versions were removed as part of the name changes (dark->midnight and such) was this on purpose?

As a side note, I found the original scheme to be a bit more readable. The current update removed the contrast between the sidebar and editor.  Would you consider an additional option to include the original "Dark/Dark Italic" theme? :)

**Comment by michael-andreuzza** [comment]
Hey Joe, the italics versions are actually the ones deployed, and I left a snippet that removes the italics on the read me. I won't deploy other versions of the theme in this package, but I will publish the old version soon as stand-alone and without updates.  So those that want to keep it is just to download it.

I am still putting up altogether on the new versions, I wasn't ready 100% tomorrow I will be ready.

**Comment by david-gorski** [comment]
Glad to hear the old version will be republished. Already missing it. Will that be available on the marketplace or just as a release on this repo?

**Comment by joekaiser** [comment]
Glad to hear the old version is coming back :raised_hands:

**Comment by michael-andreuzza** [comment]
> Glad to hear the old version will be republished. Already missing it. Will that be available on the marketplace or just as a release on this repo?

I will publish it  @david-gorski

**Comment by michael-andreuzza** [comment]
@joekaiser @david-gorski here is the old verson guys

 https://marketplace.visualstudio.com/items?itemName=wicked-labs.old-serendipity
Only three themes.

Light, dark, and high contrast they are Italics, thereäs a snippet on th read.me to disable them.

**Comment by joekaiser** [comment]
You are the best :pray:
