### ISSUE TITLE
Feature Request: Markdown File Syntax Highlighting

### ISSUE THREAD

**Issue by whippingdot** [michael-andreuzza/serendipity#14]
I use markdown files frequently, and I used to use One Dark Pro as my theme before this. The one dark pro theme for markdown just looks better to me - and I think it is because the headings have bold to them while your headings don't. I hope maybe you can give a little bold to your headings to differentiate themselves from the rest of the text.

Also for some reason in One Dark Pro, the text size is bigger in markdown files than all the other extensions. If you could give an option in settings to also enable this it would be nice so I could have enlargened text for the markdown previews of files!

**Comment by michael-andreuzza** [comment]
try with this on your settings.json
"heading.2.markdown": "bold"

**Comment by whippingdot** [comment]
didn't change a thing

**Comment by whippingdot** [comment]
still no change for some reason...
im using the midnight version btw

**Comment by whippingdot** [comment]
Lots of people had tried telling me to use 'tokenColorCustomization' but it never seems to work...

**Comment by michael-andreuzza** [comment]
well youare going to make sone research on the vs code docs I am afraid.
