### ISSUE TITLE
Missing e in the banner

### ISSUE THREAD

**Issue by madx** [michael-andreuzza/serendipity#9]
Hi, you've got a missing `e` in `theme` in your headline:

<img width="165" alt="image" src="https://user-images.githubusercontent.com/5723/148773279-367d3d1a-8292-45cf-8048-5f0cdcb5aabb.png">

I looked for the website's source code but could not find it so I'm reporting this here

**Comment by michael-andreuzza** [comment]
Thank you Madx, is fixed!
